### ISSUE TITLE
passing params on command line

### ISSUE THREAD

**Issue by benjamincensier** [FilipDominec/python-meep-utils#2]
Hello,

Congrats for your work on this!

I'm trying to use `cylindrical_cavity.py` as a starting point for a simulation.
I ran the corresponding example "ringdown_cylindrical_cavity" with the `batch.sh` script, and it seems to do fine.
There is however this error message:

```
File "../cylindrical_cavity.py", line 14, in <module>
    sim_param, model_param = meep_utils.process_param(sys.argv[1:])
ValueError: need more than 0 values to unpack
```

due to the fact that the python script is called without argument I presume. Anyway, I get some results.

Now when I take the `cylindrical_cavity.py` script, and try to run it on the command line without argument, I have the same error message, and no output data at all.
If I try to pass some argument on the command line, like `./cylindrical_cavity X=1c Y=1G` (X and Y being some string, one of my question is actually very basic: where do I find a parameter list?):
- if I pass one argument, I get: 

```
Traceback (most recent call last):
  File "./cylindrical_cavity.py", line 14, in <module>
    sim_param, model_param = meep_utils.process_param(sys.argv[1:])
ValueError: need more than 1 value to unpack
```
- if I pass 2 arguments, I get:

```
Traceback (most recent call last):
  File "./cylindrical_cavity.py", line 51, in <module>
    model = HollowCyl_model(**model_param)
TypeError: type object argument after ** must be a mapping, not str
```

I don't understand those errors, neither am I sure of understanding what the parameters can be and which one are necessary.

also, the incriminated line in `cylindrical_cavity.py` is:

`sim_param, model_param = meep_utils.process_param(sys.argv[1:])`

and in `meep_utils.py` I see:

``` python
def process_param(args):#{{{                  %% TODO include this code into Abstr..Model.init()
    """ Parse command-line parameters and store them as attributes of the model """
    model_param = {}
    for namevalue in args:
        name, value = namevalue.split("=")
        model_param[name] = phys_to_float(value)
    return model_param
```

Isn't it odd that `process_param` returns only one dic, while its call in `cylindrical_cavity.py` requests two dics as outputs ? (sim_param and model_param)

**Comment by FilipDominec** [comment]
Hi, thank you for noting this. There is obviously a discrepancy over the versions of the `cylindrical_cavity.py` simulation and `meep_utils.py` module. The latter now assumes another format of parameter passing. For instance, `scatter.py` simulation works since it has been updated. Please save your time and avoid experimenting; I will fix other scripts, too, till evening.

**Comment by benjamincensier** [comment]
thx for the quick answer, I'm still at the very beginning and will try to work from ipython in the meantime.

I used to work directly with scheme, but since python has become my main toolbox I'm trying to switch to full python. I don't know if I got everything well, but while python is the best choice for me, I find finding doc on python-meep is more difficult than on scheme meep. meep-utils could actually be my main source of doc/inspiration.

**Comment by FilipDominec** [comment]
I believe that running and modifying the scripts presented here might be the best way to building your own simulation in python-meep. Simple simulations can be directly entered into ipython, too.

The documentation of python-meep is scarce, some can be found at the INTEC/UGENT website, but it does not cover many practical aspects. Moreover, the way python-meep is autogenerated precludes the use of named parameters. Some MEEP functions are implemented in Scheme, and did not make it into `python-meep`; naturally, these have to be replaced by custom Python code. Finally, there are less python-meep users than the users of the original scheme interface. 

Still I believe that the versatility and clear syntax of the Python outweights the hardnesses noted above. I will try to help you with some basic starting simulation of your problem.

**Comment by benjamincensier** [comment]
thx a lot, I'll try to dig a little deeper. I don't have much time for this sim project, but I believe it would be great for my work to setup a set of tools for RF sims (I don't really feel like entering big licensed stuff like HFSS or COMSOL anyway, I tried them a bit in the past, too big, too costly, and I'm not even a specialist in the field).

**Comment by FilipDominec** [comment]
The cavity ringdown simulation should work flawlessly now. You can change the cylinder _radius_ and _height_ in the `example_ringdown_cylindrical_cavity/batch.sh` file. Note all units are in SI.

If you wish to change the cavity shape, you may edit the model in `./cylindrical_cavity.py`. The structure is defined by an implicit method, which may be a little hard to start with, but is very powerful once one gets familiar with it. For reference, many other models of various structures can be found in `./metamaterial_models.py`.

**Comment by FilipDominec** [comment]
Does it work for you now?

**Comment by benjamincensier** [comment]
excellent, I'll test that this afternoon and keep you informed.

**Comment by benjamincensier** [comment]
I confirm it's working now, thx again!
