### ISSUE TITLE
LDOS computation in python-meep returns <Swig Object of type 'double *'>, cannot access from Python

### ISSUE THREAD

**Issue by FilipDominec** [FilipDominec/python-meep-utils#5]
Eduardo reports in  https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05636.html that trying to access the results of ldos.ldos() after a simulation gives:

```
Swig Object of type 'double *' at xxx
```

which naturally can not be crunched by Python. 

TODO: SWIG directives have to be changed according to http://www.swig.org/Doc1.3/Library.html#Library_nn4

**Comment by FilipDominec** [comment]
The support for direct access to plain <double *> arrays from Python was added by SWIG directives during the meep compilation, see commit https://github.com/FilipDominec/python-meep-install/commit/fe83a60ea852d447d10274c3349718ce520855fa

To apply the change, `python-meep` has to be reinstalled. To spare time, you may skip the compilation, just set the `$pm_opt` variable either to `""` or to `"_mpi"` according to your setup, and repeat the SWIG-related part of installation from line https://github.com/FilipDominec/python-meep-install/blob/master/python-meep-install.sh#L145 on.

**Comment by FilipDominec** [comment]
To test it out, I added few LDOS-related commands to the `scatter.py` script, see `ldos.py` script added by the commit a8c09ec3

It returns an array of large numbers, which I cannot interpret and I have a different computation needs than LDOS at the moment. It will be nice if Eduardo or anybody else checks the physical validity of the results.

**Comment by ecabreragranado** [comment]
Dear Filip, 

thanks a lot for your rapid solution. However, I am still getting the "Swig object..." output when running your example `ldos.py` and with my code. 

I run your updated ./python-meep-install.sh script again to add LDOS support but maybe I am doing something wrong?. I attach the output log file for the installation (quite long by the way) as you suggest in the README file. 

[Ubuntu14_04.log.txt](https://github.com/FilipDominec/python-meep-utils/files/449363/Ubuntu14_04.log.txt)

**Comment by FilipDominec** [comment]
This may be an error on either side, but surely we can clear it out. Do you compile with MPI support? How does the python-meep/meep_mpi.i look like? What do you get from `ls -l /usr/local/lib/python2.7/dist-packages/meep_mpi.py` ?

**Comment by ecabreragranado** [comment]
Yes, I compile with MPI. 

The output of `ls -l /usr/local/lib/python2.7/dist-packages/meep_mpi.py` 

is:

`-rw-r--r-- 1 root staff 262497 sep  1 11:51 /usr/local/lib/python2.7/dist-packages/meep_mpi.py`

**Comment by FilipDominec** [comment]
So far so good. Now we need to check the `python-meep/meep_mpi.i` file  contents to ascertain whether the proposed fix applied automatically.

**Comment by FilipDominec** [comment]
BTW the compilation log is some HTML page, isn't it?

**Comment by ecabreragranado** [comment]
Ups, yes. Sorry about that. I attach a txt file
[Ubuntu14_04.log.txt](https://github.com/FilipDominec/python-meep-utils/files/449389/Ubuntu14_04.log.txt)

**Comment by FilipDominec** [comment]
I tried to run the installer on a fresh system under QEMU, but I am unable to do so for the moment. Could you please attach the `python-meep/meep_mpi.i` ?

**Comment by ecabreragranado** [comment]
Of course, here it is (directly paste here because github does not let me to attach it):

```
/* MEEP SWIG INTERFACE - MPI VERSION*/

%module(directors="1") meep_mpi

%include "meep-site-init.py" //must come BEFORE meep-common.i (it can contain %rename statements, which need processing before the include-statements in meep-common.i) !

%include "meep_common.i"

// workaround for openmpi feature-bug
// for details look at http://www.open-mpi.org/faq/?category=running#loading-libmpi-dynamically
%include "openmpi-bug.py"

// workaround for bug in scipy-weave (inline C in MPI mode)
%include "weave-bug.py"

%include "meep-common.py"

%pythoncode %{

PYTHON_MEEP_MODE="mpi"
master_printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n")
master_printf(">>> Welcome to Python-Meep version 1.4.2 - running in MPI mode. <<<<\n")
master_printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n")


%}
```

**Comment by FilipDominec** [comment]
It appears like if the changes from the line 
https://github.com/FilipDominec/python-meep-install/blob/master/python-meep-install.sh#L146 onwards did not apply. Did you `git pull` recently?

**Comment by ecabreragranado** [comment]
yes, `git pull` the python-meep-utils repository, then the python-meep-install. 

I have a question regarding the updated python-meep-install.sh file though. In line [148](https://github.com/FilipDominec/python-meep-install/blob/master/python-meep-install.sh#L148) and line [151](https://github.com/FilipDominec/python-meep-install/blob/master/python-meep-install.sh#L151), should not be `meep_mpi.i` instead of `meep-mpi.i`? (meep-opt is set as `--with-mpi` in line 12). 

I tried this change and now my `meep_mpi.i` file reads:

```
/* MEEP SWIG INTERFACE - MPI VERSION*/

%module(directors="1") meep_mpi

    %include "cpointer.i"
    %pointer_functions(double ,doubleP) /* added by FDominec to enable access to LDOS computation results */
    %include "carrays.i"
    %array_functions(double, doubleArray); 
%include "meep-site-init.py" //must come BEFORE meep-common.i (it can contain %rename statements, which need processing before the include-statements in meep-common.i) !

%include "meep_common.i"

// workaround for openmpi feature-bug
// for details look at http://www.open-mpi.org/faq/?category=running#loading-libmpi-dynamically
%include "openmpi-bug.py"

// workaround for bug in scipy-weave (inline C in MPI mode)
%include "weave-bug.py"

%include "meep-common.py"

%pythoncode %{

PYTHON_MEEP_MODE="mpi"
master_printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n")
master_printf(">>> Welcome to Python-Meep version 1.4.2 - running in MPI mode. <<<<\n")
master_printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n")


%}
```

However, still getting the `Swig object...` output with your example and my code...

**Comment by FilipDominec** [comment]
You were right. I made a mistake not testing the whole script and not noticing that the file is actually `meep-mpi.i`, not `meep_mpi.i`. Fixed by commit b0490a23. Thank you a lot.

**Comment by FilipDominec** [comment]
But it remains puzzling why it still refuses to access C arrays on your system. I get a simulation output with nice numbers:

```
...
Progress 0.70 of expected total 6 s
Progress 0.80 of expected total 6 s
Progress 0.90 of expected total 6 s
CMD: cd 'Slab_resolution=5.000e-06_xholesize=u_yholesize=inf'; h5tovtk 'EPS_at_t0.000e+00.h5:eps'  '-t 0' -o 'EPS_at_t0.000e+00.vtk'
CMD: cd 'Slab_resolution=5.000e-06_xholesize=u_yholesize=inf'; rm 'EPS_at_t0.000e+00.h5'

[1693663442.663306, 1684981728.3486748, 1686791157.4398937, 1686110220.7713857, 
1682548695.8015182, 1678132420.176817, 1682977799.0526485, 1672555284.9541445, 
1677750156.2105653, 1685053968.0351083, 1672137783.2189043, 1676899261.343723, 
1683299177.9784477, 1663204272.5019345, 1646782325.4364326, 1655064768.4424465, 
1681881357.7951393, 1709084247.162528, 1673789975.131317, 1627426049.6256037]

```

**Comment by ecabreragranado** [comment]
Done a relase upgrade to Ubuntu Xenial, upgraded swig from 2.0 to 3.0. Reinstalling again python-meep and now your example works!. To be honest, I am not completely sure if it was this change the responsible for ldos calculation to work or I messed up something with the previous installation...sorry for not being a very trustable source. My code still shows the "swig object.." but that must be my fault. I will look into it asap.

Thanks a lot for your help and your patience.

**Comment by ecabreragranado** [comment]
Solved for my code too (just a stupid error in my code). I think you can close this issue.

Thanks again!

**Comment by FilipDominec** [comment]
Thank you for bringing up this topic; it may be also useful for somebody in the future. Filip
